### ISSUE TITLE
Sorry for this Issues, is there any contact information？

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [sneffort/Kaggle-Personalized-Medicine#6]
Hi there, i am a novice to kaggle and data analysis especially NLP .  Could you please let me participate in your team?

i sent a email to @Luozhen, but got no reply yet.

**Comment by sneffort** [comment]
Thanks for your trust. We are also novices, and this time is our first time to participate in Kaggle, and we are not full time. So we are sorry to you that we don't want to add other people, or maybe we can cooperate next time. Best wishes for you.

**Comment by sneffort** [comment]
Thanks for your trust. We are also novices, and this time is our first time to participate in Kaggle, and we are not full time. So we are sorry to you that we don't want to add other people, or maybe we can cooperate next time. Best wishes for you.

**Comment by feiwofeifeixiaowo** [comment]
That's Ok, maybe next time.
